// Conformance tests: the contract the C++ codec must satisfy against the
// existing C firmware and the Python ground station codec.
//
// The fixtures in tests/fixtures.hpp are real wire bytes generated by the
// Python codec, which mirrors the firmware. Each TEST_CASE below pins one
// independent invariant — if any of them ever fails, the C++ codec has
// silently diverged from the proven implementations.
#include <catch2/catch_test_macros.hpp>
#include <catch2/generators/catch_generators.hpp>

#include "ccsds/codec.hpp"
#include "fixtures.hpp"

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>
#include <vector>

namespace {

template <std::size_t N>
std::vector<std::byte> to_bytes(const std::array<std::uint8_t, N>& a) {
    std::vector<std::byte> v;
    v.reserve(N);
    for (auto b : a) v.push_back(std::byte{b});
    return v;
}

std::span<const std::byte> as_byte_span(const std::vector<std::byte>& v) {
    return std::span<const std::byte>(v.data(), v.size());
}

// Build the logical Packet that, when encoded, must produce the fixture.
ccsds::Packet hk_logical() {
    ccsds::Packet p;
    p.type      = ccsds::PacketType::TM;
    p.apid      = ccsds::Apid::HK;
    p.seq_flags = ccsds::SeqFlags::UNSEGMENTED;
    p.seq_count = 7;
    // Payload bytes from fixtures.hpp (the inner [6 .. n-2] window).
    static constexpr std::array<std::uint8_t, 12> payload = {
        0x00, 0x12, 0xD6, 0x87, 0x09, 0x29,
        0x04, 0xB0, 0x0C, 0xE4, 0x00, 0x2A,
    };
    for (auto b : payload) p.payload.push_back(std::byte{b});
    return p;
}

ccsds::Packet event_logical() {
    ccsds::Packet p;
    p.type      = ccsds::PacketType::TM;
    p.apid      = ccsds::Apid::EVENT;
    p.seq_flags = ccsds::SeqFlags::UNSEGMENTED;
    p.seq_count = 12;
    static constexpr std::array<std::uint8_t, 4> payload = {
        0x01, 0x00, 0x00, 0x11,
    };
    for (auto b : payload) p.payload.push_back(std::byte{b});
    return p;
}

ccsds::Packet ping_logical() {
    ccsds::Packet p;
    p.type      = ccsds::PacketType::TC;
    p.apid      = ccsds::Apid::CMD;
    p.seq_flags = ccsds::SeqFlags::UNSEGMENTED;
    p.seq_count = 1;
    p.payload.push_back(std::byte{0x01});  // CMD_PING
    return p;
}

ccsds::Packet set_tm_rate_logical() {
    ccsds::Packet p;
    p.type      = ccsds::PacketType::TC;
    p.apid      = ccsds::Apid::CMD;
    p.seq_flags = ccsds::SeqFlags::UNSEGMENTED;
    p.seq_count = 2;
    static constexpr std::array<std::uint8_t, 5> payload = {
        0x03, 0x00, 0x00, 0x01, 0xF4,
    };
    for (auto b : payload) p.payload.push_back(std::byte{b});
    return p;
}

}  // namespace

TEST_CASE("round-trip: encode then decode reconstructs the packet",
          "[conformance][roundtrip]") {
    auto p = GENERATE(hk_logical(), event_logical(),
                      ping_logical(), set_tm_rate_logical());
    const auto frame = ccsds::encode(p);
    const auto round = ccsds::decode(frame);
    REQUIRE(round.has_value());
    REQUIRE(round->type      == p.type);
    REQUIRE(round->apid      == p.apid);
    REQUIRE(round->seq_flags == p.seq_flags);
    REQUIRE(round->seq_count == p.seq_count);
    REQUIRE(round->payload   == p.payload);
}

TEST_CASE("byte-identical: C++ encode matches the proven fixture bytes",
          "[conformance][cross-impl]") {
    using namespace ccsds::fixtures;
    SECTION("HK telemetry")   { REQUIRE(ccsds::encode(hk_logical())          == to_bytes(hk_tm_frame)); }
    SECTION("EVENT telemetry"){ REQUIRE(ccsds::encode(event_logical())       == to_bytes(event_tm_frame)); }
    SECTION("PING TC")        { REQUIRE(ccsds::encode(ping_logical())        == to_bytes(ping_tc_frame)); }
    SECTION("SET_TM_RATE TC") { REQUIRE(ccsds::encode(set_tm_rate_logical()) == to_bytes(set_tm_rate_tc_frame)); }
}

TEST_CASE("decode parses every fixture into the expected fields",
          "[conformance][decode]") {
    using namespace ccsds::fixtures;

    SECTION("HK telemetry") {
        const auto frame = to_bytes(hk_tm_frame);
        const auto pkt   = ccsds::decode(as_byte_span(frame));
        REQUIRE(pkt.has_value());
        REQUIRE(pkt->type      == ccsds::PacketType::TM);
        REQUIRE(pkt->apid      == ccsds::Apid::HK);
        REQUIRE(pkt->seq_count == 7);
        REQUIRE(pkt->payload.size() == 12);
    }
    SECTION("EVENT telemetry") {
        const auto frame = to_bytes(event_tm_frame);
        const auto pkt   = ccsds::decode(as_byte_span(frame));
        REQUIRE(pkt.has_value());
        REQUIRE(pkt->type      == ccsds::PacketType::TM);
        REQUIRE(pkt->apid      == ccsds::Apid::EVENT);
        REQUIRE(pkt->seq_count == 12);
    }
    SECTION("SET_TM_RATE TC") {
        const auto frame = to_bytes(set_tm_rate_tc_frame);
        const auto pkt   = ccsds::decode(as_byte_span(frame));
        REQUIRE(pkt.has_value());
        REQUIRE(pkt->type      == ccsds::PacketType::TC);
        REQUIRE(pkt->apid      == ccsds::Apid::CMD);
        REQUIRE(pkt->seq_count == 2);
        REQUIRE(pkt->payload.size() == 5);
        REQUIRE(std::to_integer<std::uint8_t>(pkt->payload[0]) ==
                static_cast<std::uint8_t>(ccsds::Command::SET_TM_RATE));
    }
}

TEST_CASE("byte-identical: decode-then-re-encode reproduces the wire bytes",
          "[conformance][cross-impl][reencode]") {
    // The strongest single test: take frames produced by the *other*
    // implementations, parse them with C++, re-encode them with C++,
    // and require byte-for-byte equality.
    using namespace ccsds::fixtures;

    auto check = [](std::span<const std::byte> original) {
        const auto pkt = ccsds::decode(original);
        REQUIRE(pkt.has_value());
        const auto re = ccsds::encode(*pkt);
        REQUIRE(std::vector<std::byte>(original.begin(), original.end()) == re);
    };
    SECTION("HK")          { check(as_byte_span(to_bytes(hk_tm_frame))); }
    SECTION("EVENT")       { check(as_byte_span(to_bytes(event_tm_frame))); }
    SECTION("PING")        { check(as_byte_span(to_bytes(ping_tc_frame))); }
    SECTION("SET_TM_RATE") { check(as_byte_span(to_bytes(set_tm_rate_tc_frame))); }
}

// --- failure modes -------------------------------------------------------

TEST_CASE("decode rejects a corrupted CRC", "[conformance][error]") {
    auto frame = to_bytes(ccsds::fixtures::ping_tc_frame);
    frame.back() = std::byte{static_cast<std::uint8_t>(
        std::to_integer<std::uint8_t>(frame.back()) ^ 0xFFu)};
    REQUIRE_FALSE(ccsds::decode(as_byte_span(frame)).has_value());
}

TEST_CASE("decode rejects a truncated frame", "[conformance][error]") {
    auto frame = to_bytes(ccsds::fixtures::hk_tm_frame);
    // Hold back the last byte — length field says one more byte is needed.
    REQUIRE_FALSE(
        ccsds::decode(std::span<const std::byte>(frame.data(), frame.size() - 1))
            .has_value());
}

TEST_CASE("decode rejects an under-minimum buffer", "[conformance][error]") {
    std::vector<std::byte> tiny(ccsds::kMinFrameLen - 1, std::byte{0});
    REQUIRE_FALSE(ccsds::decode(as_byte_span(tiny)).has_value());
}

TEST_CASE("decode rejects a wrong CCSDS version", "[conformance][error]") {
    auto frame = to_bytes(ccsds::fixtures::ping_tc_frame);
    // Top 3 bits of byte 0 are version. Set version=1 (bit 5).
    frame[0] = std::byte{static_cast<std::uint8_t>(
        std::to_integer<std::uint8_t>(frame[0]) | 0x20u)};
    REQUIRE_FALSE(ccsds::decode(as_byte_span(frame)).has_value());
}

TEST_CASE("encode rejects out-of-range fields", "[conformance][error]") {
    ccsds::Packet p = hk_logical();
    p.seq_count = 0x4000;  // > 14-bit max
    REQUIRE_THROWS_AS(ccsds::encode(p), std::invalid_argument);
}
