// Conformance fixtures: frames generated by the existing Python codec
// (ground/ccsds_codec.py) which mirrors the STM32 firmware byte-for-byte.
//
// Each fixture is the *exact* wire bytes of a real TM/TC packet that the
// firmware would emit or accept. The C++ codec must reproduce these.
//
// Format reminder:
//   [ id(2) | seq_ctl(2) | data_len(2) | payload | crc16(2) ]
//   id      = vvv t s aaaaaaaaaaa   (version=0, type, sec_hdr_flag, APID)
//   seq_ctl = ff cccccccccccccc     (flags=0b11 unsegmented, 14-bit seq)
//   data_len = (payload + crc) - 1  big-endian
//   crc     = CRC-16/CCITT-FALSE over header+payload (poly 0x1021,
//             init 0xFFFF, no refin/refout, no xorout; check = 0x29B1).
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>

namespace ccsds::fixtures {

// HK telemetry, APID 0x064, seq=7
// payload = struct.pack('>IhHHH', 1234567, 2345, 1200, 3300, 42)
inline constexpr std::array<std::uint8_t, 20> hk_tm_frame = {
    0x00, 0x64, 0xC0, 0x07, 0x00, 0x0D, 0x00, 0x12,
    0xD6, 0x87, 0x09, 0x29, 0x04, 0xB0, 0x0C, 0xE4,
    0x00, 0x2A, 0xFD, 0xA8,
};

// EVENT (ack) telemetry, APID 0x065, seq=12
// payload = struct.pack('>BBH', CMD_PING=0x01, status=0, orig_seq=0x0011)
inline constexpr std::array<std::uint8_t, 12> event_tm_frame = {
    0x00, 0x65, 0xC0, 0x0C, 0x00, 0x05, 0x01, 0x00,
    0x00, 0x11, 0x60, 0x19,
};

// PING telecommand, APID 0x0C8, seq=1, payload = [CMD_PING]
inline constexpr std::array<std::uint8_t, 9> ping_tc_frame = {
    0x10, 0xC8, 0xC0, 0x01, 0x00, 0x02, 0x01, 0x46, 0x88,
};

// SET_TM_RATE telecommand, APID 0x0C8, seq=2,
// payload = struct.pack('>BI', CMD_SET_TM_RATE=0x03, 500)
inline constexpr std::array<std::uint8_t, 13> set_tm_rate_tc_frame = {
    0x10, 0xC8, 0xC0, 0x02, 0x00, 0x06, 0x03, 0x00,
    0x00, 0x01, 0xF4, 0xCD, 0x03,
};

// Helper to view any fixture as a span of bytes.
template <std::size_t N>
constexpr std::span<const std::uint8_t> view(
    const std::array<std::uint8_t, N>& a) {
    return {a.data(), a.size()};
}

}  // namespace ccsds::fixtures
